// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  sessionId: __t.u64().name("session_id"),
  model: __t.string(),
  tick: __t.u64(),
  parentThoughtId: __t.option(__t.u64()).name("parent_thought_id"),
  text: __t.string(),
  latchWord: __t.string().name("latch_word"),
  mood: __t.string(),
  gesture: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
