// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import RetuneTimersReducer from "../retune_timers_reducer";
import SetConfigReducer from "../set_config_reducer";
import StartSessionReducer from "../start_session_reducer";

export type RetuneTimersParams = __Infer<typeof RetuneTimersReducer>;
export type SetConfigParams = __Infer<typeof SetConfigReducer>;
export type StartSessionParams = __Infer<typeof StartSessionReducer>;

